variables:
  PLUGIN: 'block_coupon'
  PATHNAME: 'blocks/coupon'
  REPOURL: 'https://github.com/sebsoftnl/moodle-block_coupon'

include:
  - project: 'sebsoft/open-source/gitlab'
    file: '/opensource-plugin/opensource-plugin-405+.yml'
    ref: main
